{
  "ok": true,
  "date": "2026-09-21",
  "count": 12,
  "response": [
    {
      "id": 10136,
      "league_id": 34,
      "season_id": 52,
      "home_team_id": 929,
      "home_team": "Criciúma",
      "away_team_id": 828,
      "away_team": "Operário-PR",
      "home_coach_id": 154,
      "away_coach_id": 161,
      "referee_id": 2357,
      "venue_id": 709,
      "event_date": "2026-09-21T22:30:00+00:00",
      "status": "notstarted",
      "replaced_by": null,
      "round_number": 29,
      "round_name": "",
      "group_name": null,
      "stage": "regular-season",
      "stage_name": "Regular season",
      "round_label": "Regular season · Matchday 29",
      "period": "",
      "current_minute": null,
      "home_score": null,
      "away_score": null,
      "home_score_ht": null,
      "away_score_ht": null,
      "penalty_shootout": null,
      "extra_time_score": null,
      "is_local_derby": false,
      "is_neutral_ground": false,
      "travel_distance_km": null,
      "weather": {
        "code": 2,
        "description": "cloudy",
        "wind_speed": 11,
        "temperature_c": 20
      },
      "pitch_condition": null,
      "attendance": null,
      "live_websocket": false,
      "websocket_plus": true,
      "highlights": [],
      "head_to_head": {
        "total_matches": 9,
        "home_wins": 1,
        "draws": 2,
        "away_wins": 6,
        "home_goals": 7,
        "away_goals": 12,
        "avg_total_goals": 2.11111111111111,
        "home_win_rate": 0.111111111111111,
        "away_win_rate": 0.666666666666667,
        "recent_matches": [
          {
            "away": "Criciúma",
            "date": "2026-05-24T23:30:00+00:00",
            "home": "Operário-PR",
            "score": "1-1",
            "event_id": 9953,
            "away_score": 1,
            "home_score": 1,
            "away_team_id": 929,
            "home_team_id": 828
          },
          {
            "away": "Criciúma",
            "date": "2025-08-02T00:30:00+00:00",
            "home": "Operário-PR",
            "score": "1-0",
            "event_id": 225096,
            "away_score": 0,
            "home_score": 1,
            "away_team_id": 929,
            "home_team_id": 828
          },
          {
            "away": "Operário-PR",
            "date": "2025-04-05T00:00:00+00:00",
            "home": "Criciúma",
            "score": "1-2",
            "event_id": 224901,
            "away_score": 2,
            "home_score": 1,
            "away_team_id": 828,
            "home_team_id": 929
          },
          {
            "away": "Operário-PR",
            "date": "2022-08-17T22:00:00+00:00",
            "home": "Criciúma",
            "score": "2-0",
            "event_id": 250592,
            "away_score": 0,
            "home_score": 2,
            "away_team_id": 828,
            "home_team_id": 929
          },
          {
            "away": "Criciúma",
            "date": "2022-05-07T19:30:00+00:00",
            "home": "Operário-PR",
            "score": "2-0",
            "event_id": 250405,
            "away_score": 0,
            "home_score": 2,
            "away_team_id": 929,
            "home_team_id": 828
          },
          {
            "away": "Criciúma",
            "date": "2019-11-05T23:30:00+00:00",
            "home": "Operário-PR",
            "score": "1-0",
            "event_id": 286088,
            "away_score": 0,
            "home_score": 1,
            "away_team_id": 929,
            "home_team_id": 828
          },
          {
            "away": "Operário-PR",
            "date": "2019-08-03T19:30:00+00:00",
            "home": "Criciúma",
            "score": "1-2",
            "event_id": 285897,
            "away_score": 2,
            "home_score": 1,
            "away_team_id": 828,
            "home_team_id": 929
          },
          {
            "away": "Operário-PR",
            "date": "2016-04-28T22:15:00+00:00",
            "home": "Criciúma",
            "score": "1-1",
            "event_id": 358623,
            "away_score": 1,
            "home_score": 1,
            "away_team_id": 828,
            "home_team_id": 929
          },
          {
            "away": "Criciúma",
            "date": "2016-04-13T00:00:00+00:00",
            "home": "Operário-PR",
            "score": "2-1",
            "event_id": 358651,
            "away_score": 1,
            "home_score": 2,
            "away_team_id": 929,
            "home_team_id": 828
          }
        ]
      },
